// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2022.

//! Temperature sensor driver, nRF5X-family
//!
//! Generates a simple temperature measurement without sampling
//!
//! Authors
//! -------------------
//! * Niklas Adolfsson <niklasadolfsson1@gmail.com>
//! * Fredrik Nilsson <frednils@student.chalmers.se>
//! * Date: March 03, 2017

use core::marker::PhantomData;
use core::mem::transmute;
use core::ops::Deref;

use kernel::power_manager::{Peripheral, PowerError, PowerManager, Reg, State, StateEnum, Store};
use kernel::utilities::cells::OptionalCell;
use kernel::utilities::registers::interfaces::{Readable, Writeable};
use kernel::utilities::registers::{
    register_bitfields, FieldValue, ReadOnly, ReadWrite, RegisterLongName, UIntLike, WriteOnly,
};
use kernel::utilities::StaticRef;
use kernel::ErrorCode;

use power_states::states;

pub const TEMPERATURE_BASE: usize = 0x4000C000;

// Attribute macro
// #[states(peripheral = "Nrf5xTemp", registers = RegisterBlock)]
// pub enum TemperatureStates {
//     Off,
//     Reading
// }

// Function-like macro
states!(
    peripheral_name = "Nrf5xTemp",
    registers = RegisterBlock,
    states = [
        Off => [Reading],
        Reading => [Off],
    ]
);

// -----------------------------------------------------------------------------------------
// TODO: add these to macro
impl<S: State> Nrf5xTempRegister<S> {
    // TODO: Likely want to add some capability here that restricts this.
    pub fn new() -> Nrf5xTempRegister<S> {
        let reg = unsafe { StaticRef::new(TEMPERATURE_BASE as *const RegisterBlock<S>) };
        Nrf5xTempRegister { reg: reg }
    }
}

impl ReadRegister<u32, Temperature::Register, Reading> {
    fn get(&self) -> u32 {
        self.reg.get()
    }
}

#[repr(C)]
pub struct RegisterBlock<S: State> {
    /// Start temperature measurement
    /// Address: 0x000 - 0x004
    task_start: StateChangeRegister<u32, TaskStart::Register, S>,
    /// Stop temperature measurement
    /// Address: 0x004 - 0x008
    task_stop: StateChangeRegister<u32, TaskStop::Register, S>,
    /// Reserved
    _reserved1: [u32; 62],
    /// Temperature measurement complete, data ready
    /// Address: 0x100 - 0x104
    event_datardy: ReadWriteRegister<u32, EventDataReady::Register, S>,
    /// Reserved
    // Note, `inten` register on nRF51 is ignored because it's not supported by nRF52
    // And intenset and intenclr provide the same functionality
    _reserved2: [u32; 128],
    /// Enable interrupt
    /// Address: 0x304 - 0x308
    intenset: ReadWriteRegister<u32, Intenset::Register, S>,
    /// Disable interrupt
    /// Address: 0x308 - 0x30c
    intenclr: ReadWriteRegister<u32, Intenclr::Register, S>,
    /// Reserved
    _reserved3: [u32; 127],
    /// Temperature in °C (0.25° steps)
    /// Address: 0x508 - 0x50c
    temp: ReadRegister<u32, Temperature::Register, S>,
    /// Reserved
    _reserved4: [u32; 5],
    /// Slope of piece wise linear function (nRF52 only)
    /// Address 0x520 - 0x534
    #[cfg(feature = "nrf52")]
    a: [ReadWrite<u32, A::Register>; 6],
    _reserved5: [u32; 2],
    /// y-intercept of 5th piece wise linear function (nRF52 only)
    /// Address: 0x540 - 0x554
    #[cfg(feature = "nrf52")]
    b: [ReadWrite<u32, B::Register>; 6],
    _reserved6: [u32; 2],
    /// End point of 1st piece wise linear function (nRF52 only)
    /// Address: 0x560 - 0x570
    #[cfg(feature = "nrf52")]
    pub t: [ReadWrite<u32, B::Register>; 5],
}

// End of autogenerated code //

register_bitfields! [u32,
    /// Start task
    TaskStart [
        ENABLE OFFSET(0) NUMBITS(1)
    ],

    /// Stop task
    TaskStop [
        ENABLE OFFSET(0) NUMBITS(1)
    ],

    /// Read event
    EventDataReady [
        READY OFFSET(0) NUMBITS(1)
    ],

    /// Enabled interrupt
    Intenset [
        DATARDY OFFSET(0) NUMBITS(1)
    ],

    /// Disable interrupt
    Intenclr [
        DATARDY OFFSET(0) NUMBITS(1)
    ],

    /// Temperature in °C (0.25° steps)
    Temperature [
        TEMP OFFSET(0) NUMBITS(32)
    ],

    /// Slope of piece wise linear function
    A [
        SLOPE OFFSET(0) NUMBITS(12)
    ],

    /// y-intercept of wise linear function
    B [
        INTERCEPT OFFSET(0) NUMBITS(14)
    ],

    /// End point of wise linear function
    T [
       PIECE OFFSET(0) NUMBITS(8)
    ]
];

pub struct Temp<'a, PM: PowerManager<Nrf5xTempPeripheral>> {
    client: OptionalCell<&'a dyn kernel::hil::sensors::TemperatureClient>,
    power_manager: &'a PM,
}

impl<'a, PM: PowerManager<Nrf5xTempPeripheral>> Temp<'a, PM> {
    pub fn new(pm: &'a PM) -> Temp<'a, PM> {
        Temp {
            client: OptionalCell::empty(),
            power_manager: pm,
        }
    }

    /// Temperature interrupt handler
    pub fn handle_interrupt(&self) {
        // TODO: Anthony is working on a way for this to be outside the interrupt handler. Placing this here
        // for now.
        let _ = self.power_manager.use_power_expecting::<_, Reading>(|reg| {
            // disable interrupts
            self.disable_interrupts(&reg);

            // get temperature
            // Result of temperature measurement in °C, 2's complement format, 0.25 °C steps
            let temp = (reg.temp.get() as i32 * 100) / 4;

            // stop measurement
            let reg_result = reg.into_off(self.power_manager);

            // trigger callback with temperature
            self.client.map(|client| client.callback(Ok(temp)));

            // TODO: helper to handle this and place into enum.
            match reg_result {
                Ok(reg) => Ok(reg.into()),
                Err(PowerError(val, error)) => Err(PowerError(val.into(), error)),
            }
        });
    }

    fn enable_interrupts<S: OffStateReadingState>(&self, reg: &Nrf5xTempRegister<S>) {
        reg.intenset.write(Intenset::DATARDY::SET);
    }

    fn disable_interrupts<S: OffStateReadingState>(&self, reg: &Nrf5xTempRegister<S>) {
        reg.intenclr.write(Intenclr::DATARDY::SET);
    }
}

impl<'a, PM: PowerManager<Nrf5xTempPeripheral>> kernel::hil::sensors::TemperatureDriver<'a>
    for Temp<'a, PM>
{
    fn read_temperature(&self) -> Result<(), ErrorCode> {
        self.power_manager
            .use_power_expecting::<_, Off>(|reg: Nrf5xTempRegister<Off>| {
                self.enable_interrupts(&reg);
                reg.event_datardy.write(EventDataReady::READY::CLEAR);
                let reg_result: Result<
                    Nrf5xTempRegister<Reading>,
                    PowerError<Nrf5xTempRegister<Off>>,
                > = reg.into_reading(self.power_manager);

                match reg_result {
                    Ok(reg) => Ok(reg.into()),
                    Err(PowerError(val, error)) => Err(PowerError(val.into(), error)),
                }
            })
    }

    fn set_client(&self, client: &'a dyn kernel::hil::sensors::TemperatureClient) {
        self.client.set(client);
    }
}
